name: all_in_one
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.1.4
  get_storage: ^2.0.2
  flutter_zoom_drawer: ^2.0.2+4
  
  rxdart: ^0.27.1


  # 전화걸기. QR 코드 스캔 후 전화 걸기.
  flutter_phone_direct_caller: ^2.0.0

  # 아이콘 모음집
  fluttericon: ^2.0.0


  webview_flutter: ^2.0.8

  # x_flutter: ^0.0.7
  x_flutter:
    path: packages/subtrees/x_flutter

  widgets:
    path: packages/widgets

  services:
    path: packages/services

  calculator:
    path: packages/features/calculator

  qr_code:
    path: packages/features/qr_code

  weather:
    path: packages/features/weather

  kakaomap_webview:
    path: packages/features/kakaomap_webview
    
dependency_overrides:
  # flutter_simple_calculator 에서 패키지 함수 리턴 타입 관련 빌드 에러 발생하여 추가.
  expressions: ^0.2.2

  # expressions 패키지에서 사용하는 rxdart 버전이 다른 패키지와 달라서, 최신 버전으로 변경
  rxdart: ^0.27.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
flutter:
  uses-material-design: true
